/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mymain.java
 *
 * Created on 31 Jan, 2011, 12:32:36 AM
 */

package assi3;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;

/**
 *
 * @author user
 */
public class mymain extends javax.swing.JFrame {
double firstnum;
double secondnum;
double ans;
int plusclick=0;
int minusclick=0;
int divideclick=0;
int multiplyclick=0;
int decimalclick=0;
int ansclick=0;
int sinabclick=0;
int cosabclick=0;
int ncrclick=0;
int pnrclick=0;
int enterclick=0;
int printed=0;
    /** Creates new form mymain */
    public mymain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num3 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        numdec = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        clear = new javax.swing.JButton();
        sinx = new javax.swing.JButton();
        sinab = new javax.swing.JButton();
        ncr = new javax.swing.JButton();
        cosab = new javax.swing.JButton();
        npr = new javax.swing.JButton();
        add = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        answer = new javax.swing.JButton();
        factorial = new javax.swing.JButton();
        C = new javax.swing.JButton();
        plusminus = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        cosx = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        Enter = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        numdec.setText(".");
        numdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numdecActionPerformed(evt);
            }
        });

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        screen.setColumns(20);
        screen.setEditable(false);
        screen.setRows(5);
        jScrollPane1.setViewportView(screen);

        clear.setText("CLEAR");
        clear.setToolTipText("clears the screen");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        sinx.setText("sin(x)");
        sinx.setToolTipText("press after entering value");
        sinx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinxActionPerformed(evt);
            }
        });

        sinab.setText("sin(a+b)");
        sinab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinabActionPerformed(evt);
            }
        });

        ncr.setText("nCr");
        ncr.setToolTipText("press and enter values");
        ncr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncrActionPerformed(evt);
            }
        });

        cosab.setText("cos(a+b)");
        cosab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosabActionPerformed(evt);
            }
        });

        npr.setText("nPr");
        npr.setToolTipText("press and enter values");
        npr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nprActionPerformed(evt);
            }
        });

        add.setText("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        answer.setText("ANS");
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });

        factorial.setText("n!");
        factorial.setToolTipText("press after entering value");
        factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialActionPerformed(evt);
            }
        });

        C.setText("C");
        C.setToolTipText("backspace");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        plusminus.setText("+/-");
        plusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminusActionPerformed(evt);
            }
        });

        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        cosx.setText("cos(x)");
        cosx.setToolTipText("press after entering value");
        cosx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosxActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        Enter.setText("ENTER");
        Enter.setToolTipText("press to enter another argument");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setText("HELLO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(num4)
                                                .addGap(18, 18, 18)
                                                .addComponent(num5))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Enter)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                    .addGap(17, 17, 17)
                                                    .addComponent(num2)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(num7)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(num8))))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cosx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sinx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                        .addGap(45, 45, 45)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cosab, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(sinab, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(num6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(num3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(num9))))))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(multiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numdec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(plusminus)
                            .addGap(2, 2, 2))
                        .addComponent(divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(factorial, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(npr, 0, 0, Short.MAX_VALUE)
                            .addComponent(minus, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(ncr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(C, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C)
                    .addComponent(numdec)
                    .addComponent(num3)
                    .addComponent(num2)
                    .addComponent(num1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(plusminus)
                    .addComponent(num6)
                    .addComponent(num5)
                    .addComponent(num4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minus)
                    .addComponent(multiply)
                    .addComponent(num9)
                    .addComponent(num8)
                    .addComponent(num7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factorial)
                    .addComponent(divide)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinx)
                    .addComponent(ncr)
                    .addComponent(sinab))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cosx)
                            .addComponent(npr)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cosab)))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
     screen.append("1");      // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
screen.append("2");        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
screen.append("3");        // TODO add your handling code here:
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        screen.append("4");// TODO add your handling code here:
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
screen.append("5");        // TODO add your handling code here:
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
screen.append("6");        // TODO add your handling code here:
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
screen.append("7");        // TODO add your handling code here:
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
screen.append("8");        // TODO add your handling code here:
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
screen.append("9");        // TODO add your handling code here:
    }//GEN-LAST:event_num9ActionPerformed

    private void numdecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numdecActionPerformed
if(decimalclick==0){
    screen.append(".");        // TODO add your handling code here:
    decimalclick=1;
        }
    }//GEN-LAST:event_numdecActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
screen.append("0");        // TODO add your handling code here:
    }//GEN-LAST:event_zeroActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
label1.setText("");
        screen.setText("");        // TODO add your handling code here:
decimalclick=0;
    }//GEN-LAST:event_clearActionPerformed

    private void sinxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinxActionPerformed
          double x;
          x=Double.parseDouble(screen.getText());
          x=Math.sin(x);
          screen.setText(Double.toString(x));// TODO add your handling code here:
          label1.setText("sin(x)=");
          decimalclick=1;

    }//GEN-LAST:event_sinxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          double x;
          x=Double.parseDouble(screen.getText());
          x=Math.cos(x);
          screen.setText(Double.toString(x));        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
    int i,j;
    char c[];
    String s;
    s=screen.getText();// TODO add your handling code here:
    i=s.length();
    //System.out.printf("i=%d",i);
    if(i>1){
        c=s.toCharArray();
    //screen.setText(s);
    char temp[]=new char[i-1];
    for(j=0;j<i-1;++j){
        temp[j]=c[j];
    }
    if(c[i-1]=='.')
        decimalclick=0;
    String str=new String(temp);
    screen.setText(str);}
 else screen.setText("");
    return;        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        decimalclick=0;
        ansclick=1;
        firstnum=Double.parseDouble(screen.getText());
        screen.setText("");
        plusclick=1; minusclick=0;divideclick=0;multiplyclick=0;

// TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void plusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminusActionPerformed
          double x;
          x=Double.parseDouble(screen.getText());// TODO add your handling code here:
          x=-x;
          screen.setText(Double.toString(x));
    }//GEN-LAST:event_plusminusActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
           int a,b,c;
       /* if(enterclick==1&&(ncrclick==1||pnrclick==1)){
            screen.setText(Integer.toString((int)ans));
        }*/
         if(enterclick==1)
        {
           secondnum = Double.parseDouble(screen.getText());
           enterclick=2;
        }
      if(sinabclick==1&&enterclick==2)
      {
          ans=Math.sin(firstnum + secondnum);
          screen.setText(Double.toString(Math.sin(firstnum + secondnum)));
          label1.setText("sin(a+b)=");
          enterclick=0;ncrclick=0;cosabclick=0;
        sinabclick=0;pnrclick=0;printed=1;
          return;
        }
      else if(cosabclick==1&&enterclick==2)
      {
          ans=Math.cos(firstnum + secondnum);
          screen.setText(Double.toString(Math.cos(firstnum + secondnum)));
          label1.setText("cos(a+b)=");
          enterclick=0;ncrclick=0;cosabclick=0;
        sinabclick=0;pnrclick=0;printed=1;
          return;
      }
      else if(ncrclick==1&&enterclick==2)
      {
          a=factorial((int)firstnum);
          b=factorial((int)secondnum);
          c=factorial((int)firstnum-(int)secondnum);
          ans=a/(b*c);
          screen.setText(Integer.toString(a/(b*c)));
          label1.setText("nCr=");
          enterclick=0;ncrclick=0;cosabclick=0;
        sinabclick=0;pnrclick=0;printed=1;
          return;
      }
      else if(pnrclick==1&&enterclick==2)
      {
          a=factorial((int)firstnum);
          c=factorial((int)firstnum-(int)secondnum);
          screen.setText(Integer.toString(a/c));
          label1.setText("nPr=");
          ans=a/c;
          enterclick=0;ncrclick=0;cosabclick=0;
        sinabclick=0;pnrclick=0;printed=1;
          return;
      }
        enterclick=0;ncrclick=0;cosabclick=0;
        sinabclick=0;pnrclick=0;printed=1;
        if(screen.getText().length()!=0)
        {
          secondnum = Double.parseDouble(screen.getText());
         if(plusclick==1)
        ans=firstnum+secondnum;
        else if(minusclick==1)
            ans=firstnum-secondnum;
        else if(divideclick==1)
            ans=firstnum/secondnum;
        else if(multiplyclick==1)
            ans=firstnum*secondnum;
        screen.setText(Double.toString(ans));
        ans=0;
        plusclick=0; minusclick=0;divideclick=0;multiplyclick=0;ansclick=0;decimalclick=1;
        label1.setText("ans=");
        return;
        }

    }//GEN-LAST:event_answerActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        decimalclick=0;
        ansclick=1;
        firstnum=Double.parseDouble(screen.getText());
        screen.setText("");
        plusclick=0; minusclick=1;divideclick=0;multiplyclick=0;
    }//GEN-LAST:event_minusActionPerformed

    private void cosxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosxActionPerformed
          double x;
          x=Double.parseDouble(screen.getText());
          x=Math.cos(x);
          screen.setText(Double.toString(x));
          label1.setText("cos(x)=");
          decimalclick=1;
    }//GEN-LAST:event_cosxActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        decimalclick=0;
        ansclick=1;
        firstnum=Double.parseDouble(screen.getText());
        screen.setText("");
        plusclick=0; minusclick=0;divideclick=0;multiplyclick=1;
    }//GEN-LAST:event_multiplyActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        decimalclick=0;
        ansclick=1;
        firstnum=Double.parseDouble(screen.getText());
        screen.setText("");
        plusclick=0; minusclick=0;divideclick=1;multiplyclick=0;
    }//GEN-LAST:event_divideActionPerformed

    private void factorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialActionPerformed
        int m,n=1,k;
        int i;
        if(screen.getText().length()!=0){
        m=(Integer.parseInt(screen.getText()));
     /*   for(i=m;i>=1;--i){
            n=n*i;
        }*/
        k=factorial(m);
        if(k<1){
            //label1.setText("Enter\n");
            label1.setText("smaller value\n");
            return;
        }
        screen.setText(Integer.toString(factorial(m)));
        label1.setText("n!=");
        }

    }//GEN-LAST:event_factorialActionPerformed


    private void sinabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinabActionPerformed
        screen.setText("");
        label1.setText("a=");
        enterclick=0;ncrclick=0;cosabclick=0;
        sinabclick=1;pnrclick=0;printed=1;
        //firstnum=Double.parseDouble(screen.getText());

    }//GEN-LAST:event_sinabActionPerformed
public int factorial(int n){
    int i,w=1;
    for(i=n;i>=1;--i){
        w=w*i;
    }
    return w;

}
    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        int a,b,c;
        if((sinabclick==0)&&(cosabclick==0)&&(ncrclick==0)&&(pnrclick==0))
        {
            label1.setText("function?");
             return;
        }
           
        if(enterclick==0&&((sinabclick==1)||(cosabclick==1))){
           firstnum = Double.parseDouble(screen.getText());
           enterclick=1;
           screen.setText("");
           label1.setText("b=");
           //label1.setText("Press ENTER");
            return;
        }
 else if(enterclick==0&&((ncrclick==1)||(pnrclick==1))){
           firstnum= Double.parseDouble(screen.getText());
           enterclick=1;
           screen.setText("");
           label1.setText("r=");
           //label1.setText("Press ENTER");
            return;
 }
        /*if(enterclick==1)
        {
           secondnum = Double.parseDouble(screen.getText());
           enterclick=2;
        }
      if(sinabclick==1&&enterclick==2)
      {
          ans=Math.sin(firstnum + secondnum);
          screen.setText(Double.toString(Math.sin(firstnum + secondnum)));
          label1.setText("sin(a+b)=");
        }
      else if(cosabclick==1&&enterclick==2)
      {
          ans=Math.cos(firstnum + secondnum);
          screen.setText(Double.toString(Math.cos(firstnum + secondnum)));
          label1.setText("cos(a+b)=");
      }
      else if(ncrclick==1&&enterclick==2)
      { 
          a=factorial((int)firstnum);
          b=factorial((int)secondnum);
          c=factorial((int)firstnum-(int)secondnum);
          ans=a/(b*c);
          screen.setText(Integer.toString(a/(b*c)));
          label1.setText("nCr=");
      }
      else if(pnrclick==1&&enterclick==2)
      {
          a=factorial((int)firstnum);
          c=factorial((int)firstnum-(int)secondnum);
          screen.setText(Integer.toString(a/c));
          label1.setText("nPr=");
          ans=a/c;
      }
        enterclick=0;ncrclick=0;cosabclick=0;
        sinabclick=0;pnrclick=0;printed=1;*/
    }//GEN-LAST:event_EnterActionPerformed

    private void cosabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosabActionPerformed
        screen.setText("");
        enterclick=0;ncrclick=0;cosabclick=1;
        sinabclick=0;pnrclick=0;printed=1;
        label1.setText("a=");
    }//GEN-LAST:event_cosabActionPerformed

    private void ncrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncrActionPerformed
        enterclick=0;ncrclick=1;cosabclick=0;
        sinabclick=0;pnrclick=0;printed=1;
        screen.setText("");
        label1.setText("n=");
    }//GEN-LAST:event_ncrActionPerformed

    private void nprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nprActionPerformed
        enterclick=0;ncrclick=0;cosabclick=0;
        sinabclick=0;pnrclick=1;printed=1;
        screen.setText("");
        label1.setText("n=");
    }//GEN-LAST:event_nprActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mymain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C;
    private javax.swing.JButton Enter;
    private javax.swing.JButton add;
    private javax.swing.JButton answer;
    private javax.swing.JButton clear;
    private javax.swing.JButton cosab;
    private javax.swing.JButton cosx;
    private javax.swing.JButton divide;
    private javax.swing.JButton factorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton ncr;
    private javax.swing.JButton npr;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton numdec;
    private javax.swing.JButton plusminus;
    private javax.swing.JTextArea screen;
    private javax.swing.JButton sinab;
    private javax.swing.JButton sinx;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables

}
