
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * orderform.java
 *
 * Created on 8 Apr, 2011, 8:59:08 PM
 */

/**
 *
 * @author user
 */
public class orderform extends javax.swing.JFrame {

    /** Creates new form orderform */
    public orderform() {
        initComponents();
//****************************************************************
        Scanner in = null;
        String m;
        try {
            in = new Scanner(new File("branch/branches.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(orderform.class.getName()).log(Level.SEVERE, null, ex);
        }
//addd the name of branchesin the combo boxes
        while(in.hasNext()){
            //m=in.next();
            m=in.nextLine();
            combosender.addItem(m);
            comborec.addItem(m);
        }
//****************************************************************

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tweight = new javax.swing.JTextField();
        torderdate = new javax.swing.JTextField();
        tdestination = new javax.swing.JTextField();
        tsender = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        combosender = new javax.swing.JComboBox();
        comborec = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        radiosmall = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelhide = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tvolume = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tdistance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweightActionPerformed(evt);
            }
        });

        jLabel1.setText("Weight(in kg)");

        jLabel3.setText("Order Date");

        jLabel4.setText("Destination Address");

        jLabel5.setText("Sender's Address");

        jLabel6.setText("Sender Branch");

        jLabel7.setText("Receiving  Branch");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("NEW ORDER");

        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        combosender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        comborec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        radiosmall.setText("Small article");
        radiosmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiosmallActionPerformed(evt);
            }
        });

        jLabel10.setText("For small article ");

        jLabel9.setText("and letters enter");

        jLabel11.setText("select small article option");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radiosmall)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radiosmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel12.setText("Distance(in Km)");

        jLabel2.setText("Volume(in m3)");

        javax.swing.GroupLayout panelhideLayout = new javax.swing.GroupLayout(panelhide);
        panelhide.setLayout(panelhideLayout);
        panelhideLayout.setHorizontalGroup(
            panelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tdistance)
                    .addComponent(tvolume, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelhideLayout.setVerticalGroup(
            panelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhideLayout.createSequentialGroup()
                .addGroup(panelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tdistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comborec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(tsender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(combosender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tdestination, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(torderdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(tweight, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                                .addGap(82, 82, 82)))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(panelhide, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirm)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelhide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(torderdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tdestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tsender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combosender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comborec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(confirm))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tweightActionPerformed

    //checks whether the form is correctly filled or not
    public boolean formisempty(){
        String m=(combosender.getSelectedItem()).toString();
        String n=(comborec.getSelectedItem()).toString();

        if(tweight.getText().isEmpty()==true)
            return true;
        else if(torderdate.getText().isEmpty()==true)
            return true;
        else if(tdestination.getText().isEmpty()==true)
            return true;
        else if (tsender.getText().isEmpty()==true)
            return true;
        else if(m.compareTo("SELECT ONE")==0)
            return true;
        else if(n.compareTo("SELECT ONE")==0)
            return true;
        else if(m.compareTo(n)==0)
            return true;

        if(radiosmall.isSelected()==false){
            if(tvolume.getText().isEmpty()==true||tdistance.getText().isEmpty()==true)
                 return true;
        }
            return false;
     }
//correct for non integer entries
void clearall(){
    tweight.setText("");
    tvolume.setText("");
    torderdate.setText("");
    tdestination.setText("");
    tsender.setText("");
    combosender.setSelectedIndex(0);
    comborec.setSelectedIndex(0);
    tdistance.setText("");
    return;
    
}

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        int newid=0,price=0;
        if(formisempty()==true){
      JOptionPane.showMessageDialog(this,"Please fill the form fully and correctly");
      return;
        }

        consignment neworder= new consignment(this);

        try {
            neworder.inc_con_num();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(orderform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(orderform.class.getName()).log(Level.SEVERE, null, ex);
        }
        price=neworder.price();
       JOptionPane.showMessageDialog(this, "Your Consignment ID is " + Integer.toString(neworder.ID) + "\nPrice is " + Integer.toString(price) + "\nPlease remember your consignment ID. \n You will require it in future for viewing your Consignment status \n Your receipt is being printed");

       try {
            neworder.update_consignment_database();
        } catch (IOException ex) {
            Logger.getLogger(orderform.class.getName()).log(Level.SEVERE, null, ex);
        }
       branch branch1=new branch();
       account account1=new account();
       branch1.name=combosender.getSelectedItem().toString();
        try {
            branch1.update_rev_gen(price);
            branch1.update_vol((Double.parseDouble(tvolume.getText())));
            account1.update_rev_gen(price);
        } catch (IOException ex) {
            Logger.getLogger(orderform.class.getName()).log(Level.SEVERE, null, ex);
        }

       clearall();

    }//GEN-LAST:event_confirmActionPerformed

    private void radiosmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiosmallActionPerformed
        if(radiosmall.isSelected()==true){
            panelhide.hide();
        }
        if(radiosmall.isSelected()==false){
            panelhide.setVisible(true);
        }
        return;
    }//GEN-LAST:event_radiosmallActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderform().setVisible(true);
            }
        });
    }

    
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox comborec;
    public javax.swing.JComboBox combosender;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelhide;
    public javax.swing.JRadioButton radiosmall;
    public javax.swing.JTextField tdestination;
    public javax.swing.JTextField tdistance;
    public javax.swing.JTextField torderdate;
    public javax.swing.JTextField tsender;
    public javax.swing.JTextField tvolume;
    public javax.swing.JTextField tweight;
    // End of variables declaration//GEN-END:variables

}
