
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * truckstatus.java
 *
 * Created on 10 Apr, 2011, 12:37:53 AM
 */

/**
 *
 * @author user
 */

public class truckstatus extends javax.swing.JFrame {

    /** Creates new form truckstatus */
    public truckstatus() {
        initComponents();
        /******************************************************/
        Scanner in = null,in1=null;
        String m;
        presentpanel2.setVisible(false);
        try {
            in = new Scanner(new File("truck/alltrucknum.txt"));
            in1 = new Scanner(new File("branch/branches.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(truckstatus.class.getName()).log(Level.SEVERE, null, ex);
        }
//addd the trucks in the combo boxes
        while(in.hasNext()){
            m=in.nextLine();
            trucknum.addItem(m);
        }
        while(in1.hasNext()){
            m=in1.nextLine();
            combobranch2.addItem(m);
        }
        nopanel.setVisible(false);
        yespanel.setVisible(false);
      /*********************************************/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trucknum = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        yespanel = new javax.swing.JPanel();
        currentlyyes = new javax.swing.JLabel();
        fromtext = new javax.swing.JLabel();
        totext = new javax.swing.JLabel();
        nopanel = new javax.swing.JPanel();
        currentlyno = new javax.swing.JLabel();
        attext = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        presentpanel2 = new javax.swing.JPanel();
        currentlyyes3 = new javax.swing.JLabel();
        fromtext3 = new javax.swing.JLabel();
        combobranch2 = new javax.swing.JComboBox();
        savestatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        trucknum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Truck number");

        show.setText("SHOW STATUS");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        currentlyyes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currentlyyes.setText("Currently Transporting");

        fromtext.setText("From");

        totext.setText("To");

        javax.swing.GroupLayout yespanelLayout = new javax.swing.GroupLayout(yespanel);
        yespanel.setLayout(yespanelLayout);
        yespanelLayout.setHorizontalGroup(
            yespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yespanelLayout.createSequentialGroup()
                .addGroup(yespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentlyyes)
                    .addComponent(fromtext)
                    .addComponent(totext))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        yespanelLayout.setVerticalGroup(
            yespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yespanelLayout.createSequentialGroup()
                .addComponent(currentlyyes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        currentlyno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currentlyno.setText("Currently Transporting");

        attext.setText("Currently at");

        javax.swing.GroupLayout nopanelLayout = new javax.swing.GroupLayout(nopanel);
        nopanel.setLayout(nopanelLayout);
        nopanelLayout.setHorizontalGroup(
            nopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nopanelLayout.createSequentialGroup()
                .addGroup(nopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentlyno)
                    .addComponent(attext))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        nopanelLayout.setVerticalGroup(
            nopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nopanelLayout.createSequentialGroup()
                .addComponent(currentlyno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attext)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("View Truck Status");

        currentlyyes3.setFont(new java.awt.Font("Tahoma", 1, 12));
        currentlyyes3.setText("Update Current Branch");

        fromtext3.setText("Presently at");

        combobranch2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        savestatus.setText("SAVE STATUS");
        savestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savestatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout presentpanel2Layout = new javax.swing.GroupLayout(presentpanel2);
        presentpanel2.setLayout(presentpanel2Layout);
        presentpanel2Layout.setHorizontalGroup(
            presentpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presentpanel2Layout.createSequentialGroup()
                .addComponent(currentlyyes3)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(presentpanel2Layout.createSequentialGroup()
                .addComponent(fromtext3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(combobranch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(presentpanel2Layout.createSequentialGroup()
                .addComponent(savestatus)
                .addContainerGap())
        );
        presentpanel2Layout.setVerticalGroup(
            presentpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presentpanel2Layout.createSequentialGroup()
                .addComponent(currentlyyes3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(presentpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromtext3)
                    .addComponent(combobranch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(savestatus))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(trucknum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(show, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(yespanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(presentpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trucknum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(show)
                .addGap(29, 29, 29)
                .addComponent(yespanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(presentpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        
        truck truckobject=new truck();
        truckobject.gettruckrecord(this);
        presentpanel2.setVisible(true);
        return;
    }//GEN-LAST:event_showActionPerformed

    private void savestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savestatusActionPerformed
        
        truck truckobject=new truck();
        truckobject.savestatus(this);
        JOptionPane.showMessageDialog(this,"New Status has been saved");
        return;
    }//GEN-LAST:event_savestatusActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new truckstatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel attext;
    private javax.swing.JComboBox combobranch;
    private javax.swing.JComboBox combobranch1;
    public javax.swing.JComboBox combobranch2;
    public javax.swing.JLabel currentlyno;
    public javax.swing.JLabel currentlyyes;
    private javax.swing.JLabel currentlyyes1;
    private javax.swing.JLabel currentlyyes2;
    private javax.swing.JLabel currentlyyes3;
    public javax.swing.JLabel fromtext;
    private javax.swing.JLabel fromtext1;
    private javax.swing.JLabel fromtext2;
    private javax.swing.JLabel fromtext3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel nopanel;
    private javax.swing.JPanel presentpanel;
    private javax.swing.JPanel presentpanel1;
    private javax.swing.JPanel presentpanel2;
    private javax.swing.JButton savestatus;
    private javax.swing.JButton show;
    public javax.swing.JLabel totext;
    public javax.swing.JComboBox trucknum;
    public javax.swing.JPanel yespanel;
    // End of variables declaration//GEN-END:variables
}
