/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * openpage.java
 *
 * Created on 7 Feb, 2011, 1:27:15 AM
 */

package assi_6.resources;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class openpage extends javax.swing.JFrame {

    int count_stu=0,count_tea=0;
    static int open_page=0;
    /** Creates new form openpage */
    public openpage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rn = new javax.swing.JTextField();
        signins = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sn = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        teacherp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fnt = new javax.swing.JTextField();
        signint = new javax.swing.JButton();
        snt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        passt = new javax.swing.JPasswordField();
        regnum = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toggle = new javax.swing.JToggleButton();
        teacherp1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        adminfn = new javax.swing.JTextField();
        adminsign = new javax.swing.JButton();
        adminsn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        passadmin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME TO ERP SYSTEM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("STUDENT LOGIN");

        jLabel4.setText("ROLL NO");

        jLabel5.setText("PASSWORD");

        rn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnActionPerformed(evt);
            }
        });

        signins.setText("SIGN IN");
        signins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinsActionPerformed(evt);
            }
        });

        signup.setText("SIGN UP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("STUDENT REGISTRATION");

        jLabel10.setText("FIRST NAME");

        jLabel11.setText("SECOND NAME");

        sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snActionPerformed(evt);
            }
        });

        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentpLayout = new javax.swing.GroupLayout(studentp);
        studentp.setLayout(studentpLayout);
        studentpLayout.setHorizontalGroup(
            studentpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentpLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(579, Short.MAX_VALUE))
                    .addGroup(studentpLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(608, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addGroup(studentpLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(56, 56, 56)
                        .addGroup(studentpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(fn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(rn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(pass)))
                    .addComponent(jLabel10)
                    .addComponent(signins)
                    .addGroup(studentpLayout.createSequentialGroup()
                        .addComponent(signup)
                        .addContainerGap(578, Short.MAX_VALUE))
                    .addGroup(studentpLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(468, Short.MAX_VALUE))))
        );
        studentpLayout.setVerticalGroup(
            studentpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentpLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16))
                    .addGroup(studentpLayout.createSequentialGroup()
                        .addComponent(rn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(studentpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentpLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(signins))
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signup)
                .addGap(23, 23, 23))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("TEACHER LOGIN");

        jLabel7.setText("FIRST NAME");

        jLabel8.setText("PASSWORD");

        fnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fntActionPerformed(evt);
            }
        });

        signint.setText("SIGN IN");
        signint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signintActionPerformed(evt);
            }
        });

        jLabel12.setText("SECOND NAME");

        jLabel13.setText("REGISTRATION NO.");

        javax.swing.GroupLayout teacherpLayout = new javax.swing.GroupLayout(teacherp);
        teacherp.setLayout(teacherpLayout);
        teacherpLayout.setHorizontalGroup(
            teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherpLayout.createSequentialGroup()
                        .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(teacherpLayout.createSequentialGroup()
                                .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addGap(48, 48, 48)
                                .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(regnum)
                                        .addComponent(fnt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                        .addComponent(snt)))))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(teacherpLayout.createSequentialGroup()
                        .addComponent(signint)
                        .addContainerGap(278, Short.MAX_VALUE))))
        );
        teacherpLayout.setVerticalGroup(
            teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(snt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherpLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(teacherpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(teacherpLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8)))
                .addGap(28, 28, 28)
                .addComponent(signint)
                .addGap(37, 37, 37))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("ERP SYSTEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("LOG IN ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel1)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        toggle.setText("TEACHER LOGIN");
        toggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleMouseClicked(evt);
            }
        });
        toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel14.setText("ADMINISTRATOR LOGIN");

        jLabel15.setText("FIRST NAME");

        jLabel16.setText("PASSWORD");

        adminfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminfnActionPerformed(evt);
            }
        });

        adminsign.setText("SIGN IN");
        adminsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminsignActionPerformed(evt);
            }
        });

        jLabel17.setText("SECOND NAME");

        javax.swing.GroupLayout teacherp1Layout = new javax.swing.GroupLayout(teacherp1);
        teacherp1.setLayout(teacherp1Layout);
        teacherp1Layout.setHorizontalGroup(
            teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherp1Layout.createSequentialGroup()
                        .addGroup(teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(teacherp1Layout.createSequentialGroup()
                                .addGroup(teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addGap(73, 73, 73)
                                .addGroup(teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adminfn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(adminsn)
                                    .addComponent(passadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(teacherp1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(272, Short.MAX_VALUE))
                    .addGroup(teacherp1Layout.createSequentialGroup()
                        .addComponent(adminsign)
                        .addContainerGap(258, Short.MAX_VALUE))))
        );
        teacherp1Layout.setVerticalGroup(
            teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(adminfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(adminsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(passadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(adminsign)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(toggle)
                        .addGap(320, 320, 320)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teacherp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(teacherp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(toggle))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentp, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherp, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        teacherp.setVisible(false);
        teacherp.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_rnActionPerformed

    private void fntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fntActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        registrationpage1 page=new registrationpage1();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void signinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinsActionPerformed
             String roll,password,firstn,secn,g;
              Scanner in = null;
              int a;
             //roll=rn.getText();
             password=pass.getPassword().toString();
             //firstn=fn.getText();
             //secn=sn.getText();

             File myfile;
             myfile=new File("studentfiles/"+fn.getText()+"_"+sn.getText()+".txt");
             if(!myfile.exists()){
              JOptionPane.showMessageDialog(this,"You are not registered");
              rn.setText(null);
              pass.setText(null);
              fn.setText(null);
              sn.setText(null);
              return;
             }
             else{
                try {
                      in = new Scanner(new File("studentfiles/"+fn.getText()+"_"+sn.getText()+".txt"));
                   } catch (FileNotFoundException ex) {
                      Logger.getLogger(openpage.class.getName()).log(Level.SEVERE, null, ex);
                   }
                a=in.nextInt();
                if(rn.getText().compareTo(Integer.toString(a))!=0){
                   JOptionPane.showMessageDialog(this,"Roll No. not matched");
                   return;
                }
                g=String.copyValueOf(pass.getPassword());
                if(in.next().compareTo(g)!=0)
                {
                   JOptionPane.showMessageDialog(this,"Password not matched");
                   return;
                }

        }
             student st = null;
        try {
            st = new student(fn.getText(), sn.getText(), rn.getText(),0);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(openpage.class.getName()).log(Level.SEVERE, null, ex);
        }
             st.setVisible(true);
             //this.setFocusable(false);
             this.dispose();
             
    }//GEN-LAST:event_signinsActionPerformed

    private void snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleActionPerformed
        if(toggle.isSelected()){
            teacherp.setVisible(true);
            studentp.setVisible(false);
            toggle.setText("GOTO STUDENT LOGIN");        // TODO add your handling code here:
        }
        else{
               teacherp.setVisible(false);
               studentp.setVisible(true);
               toggle.setText("GOTO TEACHER LOGIN");
        }
    }//GEN-LAST:event_toggleActionPerformed

    private void toggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_toggleMouseClicked

    private void signintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signintActionPerformed
             String g;
             Scanner in = null;
             int a;

             //password=passt.getPassword().toString();
             File myfile1;
             myfile1=new File("teacherfiles/"+fnt.getText()+"_"+snt.getText()+".txt");
             if(!myfile1.exists()){
              JOptionPane.showMessageDialog(this,"You are not registered\n"+"Ask Admin For Registration");
              fnt.setText(null);
              passt.setText(null);
              regnum.setText(null);
              snt.setText(null);
              return;
             }
             else{
                try {
                      in = new Scanner(new File("teacherfiles/"+fnt.getText()+"_"+snt.getText()+".txt"));
                   } catch (FileNotFoundException ex) {
                      Logger.getLogger(openpage.class.getName()).log(Level.SEVERE, null, ex);
                   }
                a=in.nextInt();
                if(regnum.getText().compareTo(Integer.toString(a))!=0){
                   JOptionPane.showMessageDialog(this,"Registration No. not matched");
                   return;
                }
                g=String.copyValueOf(passt.getPassword());
                if(in.next().compareTo(g)!=0)
                {
                   JOptionPane.showMessageDialog(this,"Password not matched");
                   return;
                }

        }
             teacher st=new teacher(fnt.getText(),snt.getText(),regnum.getText());
             st.setVisible(true);
             //this.setFocusable(false);
             this.dispose();
    }//GEN-LAST:event_signintActionPerformed

    private void adminfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminfnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminfnActionPerformed

    private void adminsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminsignActionPerformed
              String g,q,p;
              Scanner in = null;
              int a;
             File myfile;
             myfile=new File("otherfiles/admin.txt");
             if(!myfile.exists()){

              JOptionPane.showMessageDialog(this,"No Admin Present");
              adminfn.setText(null);
              adminsn.setText(null);
              passadmin.setText(null);
              return;
        }
             else{
                try {
                      in = new Scanner(new File("otherfiles/admin.txt"));
                   } catch (FileNotFoundException ex) {
                      Logger.getLogger(openpage.class.getName()).log(Level.SEVERE, null, ex);
                   }
                
                g=adminfn.getText();
                q=adminsn.getText();
                p=String.copyValueOf(passadmin.getPassword());
                if(g.compareTo(in.next())!=0){
                    JOptionPane.showMessageDialog(this,"WRONG NAME");
                    return;
                }
                else if(q.compareTo(in.next())!=0){
                      JOptionPane.showMessageDialog(this,"WRONG NAME");
                      return;
                 }
                 else if(p.compareTo(in.next())!=0){
                   JOptionPane.showMessageDialog(this,"Password not matched");
                   return;
                }

        }
            adminpage st = null;
            st = new adminpage();
            st.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_adminsignActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                open_page=1;
                new openpage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminfn;
    private javax.swing.JButton adminsign;
    private javax.swing.JTextField adminsn;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField fnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField passadmin;
    private javax.swing.JPasswordField passt;
    private javax.swing.JTextField regnum;
    private javax.swing.JTextField rn;
    private javax.swing.JButton signins;
    private javax.swing.JButton signint;
    private javax.swing.JButton signup;
    private javax.swing.JTextField sn;
    private javax.swing.JTextField snt;
    private javax.swing.JPanel studentp;
    private javax.swing.JPanel teacherp;
    private javax.swing.JPanel teacherp1;
    private javax.swing.JToggleButton toggle;
    // End of variables declaration//GEN-END:variables

}
