/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * registrationpage1.java
 *
 * Created on 7 Feb, 2011, 12:22:05 AM
 */

package assi_6.resources;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class registrationpage1 extends javax.swing.JFrame {

    /** Creates new form registrationpage1 */
    public registrationpage1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password_tf = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        name_tf2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("REGISTRATION PAGE");

        jLabel5.setText("PASSWORD");

        jLabel1.setText("FIRST NAME");

        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jLabel2.setText("SECOND NAME");

        jLabel4.setText("Dont left spaces after any entry");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel3)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(register)
                        .addGap(263, 263, 263)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(name_tf2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(password_tf))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(name_tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(register)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private int inc_stu_num() throws FileNotFoundException{
        int a;
        Scanner in = null;
        in = new Scanner(new File("studentfiles/stu_count.txt"));
        a=in.nextInt();
        //System.out.printf("a=%d",a);
        ++a;
        try {
          BufferedWriter out = new BufferedWriter(new FileWriter("studentfiles/stu_count.txt"));
          out.write(Integer.toString(a));
          out.close();
          }catch (IOException e) {
         }
        return a;
    }



    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        int x = 0;
        if(name_tf.getText().length()!=0&&password_tf.getPassword().length!=0&&name_tf2.getText().length()!=0){
        // File filename = new File(name_tf.getText()+name_tf2.getText()+".txt" );
            File myfile,myfile1;
            myfile=new File("studentfiles/"+name_tf.getText()+"_"+name_tf2.getText()+".txt");
            myfile1=new File("studentfiles/"+name_tf.getText()+name_tf2.getText()+"_c.txt");
            if(!myfile.exists()){                       //RollNo
                try {                                   //name
                    myfile.createNewFile();             //password
                    myfile1.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(registrationpage1.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                         x=inc_stu_num();
                  JOptionPane.showMessageDialog(this,name_tf.getText()+" "+name_tf2.getText()+"\n"+"You have successfully registerd\n"+"Your Roll No. is "+Integer.toString(x));
                  }
                catch (FileNotFoundException ex) {
                Logger.getLogger(registrationpage1.class.getName()).log(Level.SEVERE, null, ex);
                 }
                BufferedWriter out = null;
                try {
                    out = new BufferedWriter(new FileWriter("studentfiles/"+name_tf.getText()+"_"+name_tf2.getText()+".txt"));
                } catch (IOException ex) {
                    Logger.getLogger(registrationpage1.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    out.write(Integer.toString(x));
                    out.newLine();
                    out.write(password_tf.getPassword());
                    out.newLine();
                    out.write(name_tf.getText()+" "+name_tf2.getText());
                    
                } catch (IOException ex) {
                    Logger.getLogger(registrationpage1.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    out.close();
                } catch (IOException ex) {
                    Logger.getLogger(registrationpage1.class.getName()).log(Level.SEVERE, null, ex);
                }
             password_tf.setText(null);
             name_tf.setText(null);
             name_tf2.setText(null);


            }
            else {
             JOptionPane.showMessageDialog(this,"User is already present\n"+"Try different name");
             password_tf.setText(null);
             name_tf.setText(null);
             name_tf2.setText(null);
             return;
             }
          }
      else {
             JOptionPane.showMessageDialog(this,"Fill all the entries");
             return;
         }
    }//GEN-LAST:event_registerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openpage openpage1= new openpage();
        openpage1.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationpage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name_tf;
    private javax.swing.JTextField name_tf2;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables

}
