/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * student.java
 *
 * Created on 7 Feb, 2011, 6:40:53 PM
 */

package assi_6.resources;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class student extends javax.swing.JFrame {
     //static int studentcount;
    /** Creates new form student */
    int roll;
    String firstn,secn,pass;



    public student(String fn,String sn,String roll,int flagc) throws FileNotFoundException {
        //initComponents(fn,sn,roll,flagc);
        initComponents();
        //panelreg.setVisible(false);
        registrationpanel.setVisible(false);
        //panelreg.setVisible(false);
        panelreg.setVisible(false);
        regsublist.setVisible(false);
//*************************************************************
        Scanner in = null;
        String m;
        try {
            in = new Scanner(new File("studentfiles/"+fn+sn+"_c"+".txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        Scanner inp2 = null;
        String m12;
        try {
            inp2 = new Scanner(new File("coursefiles/totalcourses.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        Scanner input1 = null;
        final String mn[]=new String[7];
        int i=0;
        try {
            input1 = new Scanner(new File("studentfiles/"+fn+sn+"_c"+".txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        while(input1.hasNext()&&i<=4){
            //mn[i]=input1.next();
            mn[i]=input1.nextLine();

            ++i;
        }
        while(inp2.hasNext()){
            m12=inp2.nextLine();
            //m12=inp2.next();
            sublist1.addItem(m12);
        }
        while(in.hasNext()){
            //m=in.next();
            m=in.nextLine();
            sublist.addItem(m);
        }
        listreg.setModel(new javax.swing.AbstractListModel() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return mn.length; }
            public Object getElementAt(int i) { return mn[i]; }
        });
//*************************************************************
        namedisplay(fn,sn,roll);
        gradepanel.setVisible(false);
        back.setVisible(false);
        if(checkreg()==1){
            panelreg.setVisible(true);
            }
        else
            panelreg.setVisible(false);
        if(flagc==1){
            logout.setVisible(false);
            welcome.setVisible(false);
            back.setVisible(true);
      }

    }

private int checkreg() throws FileNotFoundException{
        int a;
        Scanner in = null;
        in = new Scanner(new File("otherfiles/registration.txt"));
        a=in.nextInt();
        return a;
}
  private void namedisplay(String firstn,String secn,String number){
        fname.setText(firstn);
        sname.setText(secn);
        num.setText(number);

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rolltext = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        panelreg = new javax.swing.JPanel();
        togglegrades2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        panelreg2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        togglegrades1 = new javax.swing.JToggleButton();
        regsublist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listreg = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        panelreg1 = new javax.swing.JPanel();
        GRADES = new javax.swing.JLabel();
        togglegrades = new javax.swing.JToggleButton();
        gradepanel = new javax.swing.JPanel();
        sublist = new javax.swing.JComboBox();
        selectsubject = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        grade = new javax.swing.JLabel();
        showselected = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gradel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registrationpanel = new javax.swing.JPanel();
        sublist1 = new javax.swing.JComboBox();
        selectsubject1 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT PROFILE");

        rolltext.setFont(new java.awt.Font("Tahoma", 1, 11));
        rolltext.setText("ROLL NO.");

        fname.setFont(new java.awt.Font("Tahoma", 1, 11));
        fname.setText("HELLO");

        sname.setFont(new java.awt.Font("Tahoma", 1, 11));
        sname.setText("HELLO");

        num.setText("123456");

        welcome.setFont(new java.awt.Font("Tahoma", 1, 11));
        welcome.setText("WELCOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(welcome)
                .addGap(29, 29, 29)
                .addComponent(fname)
                .addGap(21, 21, 21)
                .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(rolltext)
                .addGap(6, 6, 6)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome)
                    .addComponent(fname)
                    .addComponent(sname))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rolltext)
                    .addComponent(num)))
        );

        togglegrades2.setText("REGISTER");
        togglegrades2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglegrades2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("REGISTER FOR CURRENT SEMESTER");

        javax.swing.GroupLayout panelregLayout = new javax.swing.GroupLayout(panelreg);
        panelreg.setLayout(panelregLayout);
        panelregLayout.setHorizontalGroup(
            panelregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
            .addComponent(togglegrades2)
        );
        panelregLayout.setVerticalGroup(
            panelregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelregLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(togglegrades2))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("SHOW REGISTERED SUBJECTS");

        togglegrades1.setText("SHOW");
        togglegrades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglegrades1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelreg2Layout = new javax.swing.GroupLayout(panelreg2);
        panelreg2.setLayout(panelreg2Layout);
        panelreg2Layout.setHorizontalGroup(
            panelreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreg2Layout.createSequentialGroup()
                .addGroup(panelreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(togglegrades1)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20))
        );
        panelreg2Layout.setVerticalGroup(
            panelreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreg2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(togglegrades1))
        );

        jScrollPane1.setViewportView(listreg);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("REGISTERED SUBJECTS");

        javax.swing.GroupLayout regsublistLayout = new javax.swing.GroupLayout(regsublist);
        regsublist.setLayout(regsublistLayout);
        regsublistLayout.setHorizontalGroup(
            regsublistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regsublistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regsublistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        regsublistLayout.setVerticalGroup(
            regsublistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regsublistLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        GRADES.setFont(new java.awt.Font("Tahoma", 1, 11));
        GRADES.setText("GRADES ");

        togglegrades.setText("SHOW");
        togglegrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglegradesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelreg1Layout = new javax.swing.GroupLayout(panelreg1);
        panelreg1.setLayout(panelreg1Layout);
        panelreg1Layout.setHorizontalGroup(
            panelreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreg1Layout.createSequentialGroup()
                .addGroup(panelreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GRADES)
                    .addComponent(togglegrades))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        panelreg1Layout.setVerticalGroup(
            panelreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreg1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(GRADES)
                .addGap(11, 11, 11)
                .addComponent(togglegrades))
        );

        sublist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        selectsubject.setText("SELECT SUBJECT");

        subject.setFont(new java.awt.Font("Tahoma", 1, 11));
        subject.setText("SUBJECT");

        grade.setFont(new java.awt.Font("Tahoma", 1, 11));
        grade.setText("GRADE");

        showselected.setText("SHOW SELECTED");
        showselected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showselectedActionPerformed(evt);
            }
        });

        jLabel2.setText("SUBJECT SELECTED");

        gradel.setText(" GRADE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("GRADES");

        javax.swing.GroupLayout gradepanelLayout = new javax.swing.GroupLayout(gradepanel);
        gradepanel.setLayout(gradepanelLayout);
        gradepanelLayout.setHorizontalGroup(
            gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradepanelLayout.createSequentialGroup()
                .addGroup(gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(gradepanelLayout.createSequentialGroup()
                        .addComponent(selectsubject)
                        .addGap(163, 163, 163)
                        .addComponent(sublist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showselected)
                    .addGroup(gradepanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(198, 198, 198)
                        .addComponent(gradel))
                    .addGroup(gradepanelLayout.createSequentialGroup()
                        .addComponent(subject)
                        .addGap(244, 244, 244)
                        .addComponent(grade)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        gradepanelLayout.setVerticalGroup(
            gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradepanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradepanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(selectsubject))
                    .addComponent(sublist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showselected)
                .addGap(11, 11, 11)
                .addGroup(gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(gradel))
                .addGap(6, 6, 6)
                .addGroup(gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subject)
                    .addComponent(grade)))
        );

        sublist1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        selectsubject1.setText("SELECT SUBJECT");

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("REGISTRATION");

        javax.swing.GroupLayout registrationpanelLayout = new javax.swing.GroupLayout(registrationpanel);
        registrationpanel.setLayout(registrationpanelLayout);
        registrationpanelLayout.setHorizontalGroup(
            registrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
            .addGroup(registrationpanelLayout.createSequentialGroup()
                .addComponent(selectsubject1)
                .addGap(152, 152, 152)
                .addComponent(sublist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(add)
        );
        registrationpanelLayout.setVerticalGroup(
            registrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationpanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(registrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationpanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(selectsubject1))
                    .addComponent(sublist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add))
        );

        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(41, 41, 41)
                .addComponent(logout))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout)
                    .addComponent(back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrationpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelreg2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regsublist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gradepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelreg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(panelreg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrationpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(panelreg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regsublist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(gradepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        //panelreg.setVisible(false);
        //panelreg.setVisible(false);
        regsublist.setVisible(false);
        panelreg.setVisible(false);
        registrationpanel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        this.dispose();
        openpage page=new openpage();
        page.setVisible(true);
        

    }//GEN-LAST:event_logoutActionPerformed

    private void togglegradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglegradesActionPerformed
         if(togglegrades.getText().compareTo("SHOW")==0){
             togglegrades.setText("HIDE");
             gradepanel.setVisible(true);
         }
         else {
             togglegrades.setText("SHOW");
             gradepanel.setVisible(false);
          }
    }//GEN-LAST:event_togglegradesActionPerformed
    private String search(String name,String course){
        Scanner input3 = null;
        Pattern m = null;
        int flag=0;
        m=Pattern.compile(name);
        Matcher mt = m.matcher(name);
        String x,a;
         try {
            input3 = new Scanner(new File("coursefiles/"+course+".txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
       while(input3.hasNext())
        {
            if(input3.next().toString().compareTo(name)==0){
                break;
            }
        }
        if(input3.hasNext()){
            a=input3.next();
            if(a.length()==1||a.length()==2)
            return a;
            else
            return null;
        }
        else
                return null;
    }
    private void showselectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showselectedActionPerformed
         Scanner input3 = null;
                  
          if((sublist.getSelectedItem()).toString().compareTo("SELECT ONE")!=0){
                    subject.setText((sublist.getSelectedItem()).toString());
                    //grade.setText(secn);
                 }
          else {
               JOptionPane.showMessageDialog(this,"Please select one\n"+"Or if no subjects are present then register first");      
               return;
            }
        String a;
          
         a=search(fname.getText()+"_"+sname.getText(),subject.getText());
         grade.setText(a);
          return;

    }//GEN-LAST:event_showselectedActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
          Scanner in1 = null;
          int flag=0;
          String a = null;
          //char b[];
                 try {
                    in1 = new Scanner(new File("studentfiles/"+fname.getText()+sname.getText()+"_c"+".txt"));
                   } catch (FileNotFoundException ex) {
                      Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
                   }
          if((sublist1.getSelectedItem()).toString().compareTo("SELECT ONE")==0){
              JOptionPane.showMessageDialog(this,"Please select one\n");
              return;
          }
                while(in1.hasNext()){
                    if(in1.next().compareTo((sublist1.getSelectedItem()).toString())==0){
                     flag=1;
                     JOptionPane.showMessageDialog(this,"Already registered subject\n");
                     break;
                     }
                }
          if(flag==0){
            BufferedWriter out = null,out5 = null;
        try {
            out = new BufferedWriter(new FileWriter("studentfiles/"+fname.getText()+sname.getText()+"_c.txt",true));
            out5 = new BufferedWriter(new FileWriter("coursefiles/"+(sublist1.getSelectedItem()).toString()+".txt",true));

        } catch (IOException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.write(sublist1.getSelectedItem().toString());
            out.newLine();
            out5.write(fname.getText()+"_"+sname.getText()+" -");
            out5.newLine();
            out.close();
            out5.close();
        } catch (IOException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(this,sublist1.getSelectedItem().toString()+" successfully added\n"+"To see changes lOG IN again");
         return;
          }
    }//GEN-LAST:event_addActionPerformed

    private void togglegrades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglegrades1ActionPerformed
         if(togglegrades1.getText().compareTo("SHOW")==0){
             togglegrades1.setText("HIDE");
             regsublist.setVisible(true);
         }
         else {
             togglegrades1.setText("SHOW");
             regsublist.setVisible(false);
          }
    }//GEN-LAST:event_togglegrades1ActionPerformed

    private void togglegrades2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglegrades2ActionPerformed
       if(registrationpanel.isShowing()){
             registrationpanel.setVisible(false);
         }
         else {
              registrationpanel.setVisible(true);
            }
    }//GEN-LAST:event_togglegrades2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
}//GEN-LAST:event_backActionPerformed

    /**
    * @param args the command line arguments
    */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new student("h", "v", "v").setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GRADES;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel grade;
    private javax.swing.JLabel gradel;
    private javax.swing.JPanel gradepanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listreg;
    private javax.swing.JButton logout;
    private javax.swing.JLabel num;
    private javax.swing.JPanel panelreg;
    private javax.swing.JPanel panelreg1;
    private javax.swing.JPanel panelreg2;
    private javax.swing.JPanel registrationpanel;
    private javax.swing.JPanel regsublist;
    private javax.swing.JLabel rolltext;
    private javax.swing.JLabel selectsubject;
    private javax.swing.JLabel selectsubject1;
    private javax.swing.JButton showselected;
    private javax.swing.JLabel sname;
    private javax.swing.JLabel subject;
    private javax.swing.JComboBox sublist;
    private javax.swing.JComboBox sublist1;
    private javax.swing.JToggleButton togglegrades;
    private javax.swing.JToggleButton togglegrades1;
    private javax.swing.JToggleButton togglegrades2;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

}
