/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * teacher.java
 *
 * Created on 7 Feb, 2011, 1:48:58 AM
 */

package assi_6.resources;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author user
 */
public class teacher extends javax.swing.JFrame {

    /** Creates new form teacher */
    public teacher(String f,String s,String r) {
        initComponents(f,s,r);
    }
    
    private void initComponents(String fn,String sn,String rg) {
        initComponents();
        entergrade.setVisible(false);
        gradepanel.setVisible(false);
        namedisplay(fn,sn,rg);
        Scanner ingrade = null;
        String m;
        try {
            ingrade = new Scanner(new File("teacherfiles/"+fn+sn+"_c"+".txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
        }

        while(ingrade.hasNext()){
            //m=ingrade.next();
            m=ingrade.nextLine();
            sublist.addItem(m);
        }

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fname = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        togglegrade = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        viewfn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        viewsn = new javax.swing.JTextField();
        gradepanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradefield = new javax.swing.JTextArea();
        subname = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        sublist = new javax.swing.JComboBox();
        show = new javax.swing.JButton();
        subjectname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        entergrade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEACHER PROFILE");

        fname.setFont(new java.awt.Font("Tahoma", 1, 11));
        fname.setText("HELLO");

        sname.setFont(new java.awt.Font("Tahoma", 1, 11));
        sname.setText("HELLO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("WELCOME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("REGISTRATION NO.");

        num.setText("123456");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(num))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fname)
                        .addGap(18, 18, 18)
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(num))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1032, Short.MAX_VALUE)
                .addComponent(logout))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        togglegrade.setText("SHOW MENU");
        togglegrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglegradeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("ALLOT GRADES");

        jLabel14.setText("FIRST NAME");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel15.setText("VIEW STUDENT PROFILE");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton6.setText("SHOW PROFILE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel18.setText("SECOND NAME");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewsn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(viewfn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(98, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(viewsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton6)
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(togglegrade))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(togglegrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gradefield.setColumns(20);
        gradefield.setRows(5);
        jScrollPane1.setViewportView(gradefield);

        subname.setFont(new java.awt.Font("Tahoma", 1, 11));
        subname.setText("SUBJECT GRADES");

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        sublist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        subjectname.setFont(new java.awt.Font("Tahoma", 1, 11));
        subjectname.setText("SUBJECT");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText(" NAME");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("GRADE");

        entergrade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        entergrade.setText("ENTER THE GRADES IN FRONT OF NAME");

        javax.swing.GroupLayout gradepanelLayout = new javax.swing.GroupLayout(gradepanel);
        gradepanel.setLayout(gradepanelLayout);
        gradepanelLayout.setHorizontalGroup(
            gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addGroup(gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sublist, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(save)
                    .addComponent(show)
                    .addComponent(subjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gradepanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addGap(72, 72, 72)
                        .addComponent(entergrade)))
                .addContainerGap())
        );
        gradepanelLayout.setVerticalGroup(
            gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sublist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(show)
                .addGap(18, 18, 18)
                .addComponent(subjectname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(entergrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(save)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)
                        .addComponent(gradepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gradepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        this.dispose();
        openpage page=new openpage();
        page.setVisible(true);

    }//GEN-LAST:event_logoutActionPerformed

    private void togglegradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglegradeActionPerformed
            if(togglegrade.getText().compareTo("SHOW MENU")==0){
             togglegrade.setText("HIDE MENU");
             gradepanel.setVisible(true);
         }
         else {
             togglegrade.setText("SHOW MENU");
             gradepanel.setVisible(false);
          }
    }//GEN-LAST:event_togglegradeActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed

        if((sublist.getSelectedItem()).toString().compareTo("SELECT ONE")!=0){
                    subjectname.setText((sublist.getSelectedItem()).toString());
                   }
             else {
               JOptionPane.showMessageDialog(this,"Please select one\n");
               return;
              }
           File file;
           file=new File("coursefiles/"+subjectname.getText()+".txt");
        try {
                 gradefield.read( new FileReader( file.getAbsolutePath() ), null );
          } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
        entergrade.setVisible(true);
           return;
    }//GEN-LAST:event_showActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
      BufferedWriter outFile = null,out1=null;
        try {
            out1 = new BufferedWriter(new FileWriter("coursefiles/"+subjectname.getText()+".txt"));
            outFile = new BufferedWriter(new FileWriter("coursefiles/"+subjectname.getText()+".txt",true));
        } catch (IOException ex) {
            Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out1.write("");
        } catch (IOException ex) {
            Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        int totalLines = gradefield.getLineCount();
           String text = gradefield.getText();
         for (int i=0; i < totalLines; i++) {
             int start = 0;
            try {
                start = gradefield.getLineStartOffset(i);
            } catch (BadLocationException ex) {
                Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
            }
               int end = 0;
            try {
                end = gradefield.getLineEndOffset(i);
            } catch (BadLocationException ex) {
                Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
            }
                 String line = text.substring(start, end);
            try {
                outFile.write(line);
            } catch (IOException ex) {
                Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                outFile.newLine();
                //outputArea.append(line);
            } catch (IOException ex) {
                Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

           try {
            outFile.flush();
        } catch (IOException ex) {
            Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            outFile.close();
        } catch (IOException ex) {
            Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this,"YOUR CHANGES HAS BEEN SAVED\n");
           return;
    }//GEN-LAST:event_saveActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Scanner in1 = null;
        File file;
        String roll;
        if(viewfn.getText().length()!=0&&viewsn.getText().length()!=0){
            file=new File("studentfiles/"+viewfn.getText()+"_"+viewsn.getText()+".txt");
            if(!file.exists()){
                JOptionPane.showMessageDialog(this,"Student not registered");
                return;
            }
            try {
                in1 = new Scanner(new File("studentfiles/"+viewfn.getText()+"_"+viewsn.getText()+".txt"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(adminpage.class.getName()).log(Level.SEVERE, null, ex);
            }
            roll=in1.next();
            student st = null;
            try {
                st = new student(viewfn.getText(),viewsn.getText(),roll,1);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(adminpage.class.getName()).log(Level.SEVERE, null, ex);
            }
            st.setVisible(true);
           // viewfn.setText("");
            //viewsn.setText("");
        } else {
            JOptionPane.showMessageDialog(this,"fill all entries");
            return;
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void namedisplay(String firstn,String secn,String number){

        fname.setText(firstn);
        sname.setText(secn);
        num.setText(number);

    }

    /**
    * @param args the command line arguments
    */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel entergrade;
    private javax.swing.JLabel fname;
    private javax.swing.JTextArea gradefield;
    private javax.swing.JPanel gradepanel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel num;
    private javax.swing.JButton save;
    private javax.swing.JButton show;
    private javax.swing.JLabel sname;
    private javax.swing.JLabel subjectname;
    private javax.swing.JComboBox sublist;
    private javax.swing.JLabel subname;
    private javax.swing.JToggleButton togglegrade;
    private javax.swing.JTextField viewfn;
    private javax.swing.JTextField viewsn;
    // End of variables declaration//GEN-END:variables

}
