
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * branchrev.java
 *
 * Created on 17 Apr, 2011, 7:06:00 PM
 */

/**
 *
 * @author user
 */
public class branchrev extends javax.swing.JFrame {

    /** Creates new form branchrev */
    //i=1 revenue i=2 expense
    public branchrev(int i) {
        initComponents();
        /*********************************************/
         Scanner in = null,in1=null;
        String m;
        try {
            in = new Scanner(new File("branch/branches.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(branchrev.class.getName()).log(Level.SEVERE, null, ex);
        }
        //addd the trucks in the combo boxes
        while(in.hasNext()){
            m=in.nextLine();
            combobranch.addItem(m);
            combobranch1.addItem(m);
        }
        if(i==1)
            panelrev.hide();
        if(i==2)
            exppanel.hide();

         /*************************************/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        revpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        combobranch = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        panelrev = new javax.swing.JPanel();
        revt = new javax.swing.JLabel();
        revtext = new javax.swing.JLabel();
        exppanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        combobranch1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        show1 = new javax.swing.JButton();
        panelrev1 = new javax.swing.JPanel();
        revt1 = new javax.swing.JLabel();
        exptext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Branch Wise Revenue Generated");

        combobranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        jLabel1.setText("Select Branch");

        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        revt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        revt.setText("Revenue Generated");

        revtext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        revtext.setText("revtext");

        javax.swing.GroupLayout panelrevLayout = new javax.swing.GroupLayout(panelrev);
        panelrev.setLayout(panelrevLayout);
        panelrevLayout.setHorizontalGroup(
            panelrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(revt)
                .addGap(34, 34, 34)
                .addComponent(revtext)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelrevLayout.setVerticalGroup(
            panelrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrevLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revt)
                    .addComponent(revtext))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout revpanelLayout = new javax.swing.GroupLayout(revpanel);
        revpanel.setLayout(revpanelLayout);
        revpanelLayout.setHorizontalGroup(
            revpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revpanelLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, revpanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(combobranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(revpanelLayout.createSequentialGroup()
                .addComponent(show)
                .addContainerGap())
            .addGroup(revpanelLayout.createSequentialGroup()
                .addComponent(panelrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        revpanelLayout.setVerticalGroup(
            revpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revpanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(revpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("Branch Wise Expense");

        combobranch1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ONE" }));

        jLabel2.setText("Select Branch");

        show1.setText("SHOW");
        show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show1ActionPerformed(evt);
            }
        });

        revt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        revt1.setText("Expense");

        exptext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exptext.setText("revtext");

        javax.swing.GroupLayout panelrev1Layout = new javax.swing.GroupLayout(panelrev1);
        panelrev1.setLayout(panelrev1Layout);
        panelrev1Layout.setHorizontalGroup(
            panelrev1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrev1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(revt1)
                .addGap(34, 34, 34)
                .addComponent(exptext)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        panelrev1Layout.setVerticalGroup(
            panelrev1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrev1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelrev1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revt1)
                    .addComponent(exptext))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout exppanelLayout = new javax.swing.GroupLayout(exppanel);
        exppanel.setLayout(exppanelLayout);
        exppanelLayout.setHorizontalGroup(
            exppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exppanelLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exppanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(combobranch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(exppanelLayout.createSequentialGroup()
                .addComponent(show1)
                .addContainerGap())
            .addGroup(exppanelLayout.createSequentialGroup()
                .addComponent(panelrev1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        exppanelLayout.setVerticalGroup(
            exppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exppanelLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(exppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobranch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelrev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(revpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(exppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        String m;
        int rev;
        panelrev.setVisible(true);
        branch branch1=new branch();
        branch1.name=combobranch.getSelectedItem().toString();
        rev=branch1.get_revenue();
        revtext.setText(Integer.toString(rev));
        return;
}//GEN-LAST:event_showActionPerformed

    private void show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show1ActionPerformed
        String m;
        int rev;
        exppanel.setVisible(true);
        branch branch1=new branch();
        branch1.name=combobranch1.getSelectedItem().toString();
        rev=branch1.get_expense();
        exptext.setText(Integer.toString(rev));
        return;
    }//GEN-LAST:event_show1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new branchrev(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox combobranch;
    public javax.swing.JComboBox combobranch1;
    private javax.swing.JPanel exppanel;
    private javax.swing.JLabel exptext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelrev;
    private javax.swing.JPanel panelrev1;
    private javax.swing.JPanel revpanel;
    private javax.swing.JLabel revt;
    private javax.swing.JLabel revt1;
    private javax.swing.JLabel revtext;
    private javax.swing.JButton show;
    private javax.swing.JButton show1;
    // End of variables declaration//GEN-END:variables

}
