
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * truckdispatch.java
 *
 * Created on 17 Apr, 2011, 10:04:08 PM
 */

/**
 *
 * @author user
 */
public class truckdispatch extends javax.swing.JFrame {

    /** Creates new form truckdispatch */
    public truckdispatch(String name, Double vol) {
        initComponents();
        truckname.setText(name);
        volume.setText(Double.toString(vol));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        truckname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        volume = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        charge = new javax.swing.JTextField();
        issue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        truckname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        truckname.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("is available with current volume");

        volume.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volume.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter the Receipt Details");

        jLabel3.setText("Fuel Charges");

        issue.setText("Issue Receipt");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(issue)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(charge))
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(truckname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(volume)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(truckname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(volume))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(issue)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        int id = 0,rev=0;
        Scanner in = null;
        BufferedWriter out = null,out1=null;
        String truckid;
        File myfile;

        try {
            in = new Scanner(new File("slips/truckslip/id.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(truckdispatch.class.getName()).log(Level.SEVERE, null, ex);
        }
        rev=in.nextInt();++rev;
        
        truckid="truck_"+Integer.toString(rev);
        myfile=new File("slips/truckslip/"+truckid+".txt");
        account account1=new account();

        try {
            myfile.createNewFile();
            out = new BufferedWriter(new FileWriter("slips/truckslip/"+truckid+".txt"));
            out.write(charge.getText());
            out1 = new BufferedWriter(new FileWriter("slips/truckslip/id.txt"));
            out1.write(Integer.toString(rev));
            account1.update_expense(Integer.parseInt(charge.getText()));
            out.close();
            out1.close();
        } catch (IOException ex) {
            Logger.getLogger(truckdispatch.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this,"Truck Receipt ID is "+truckid+"\nRemeber this ID and enter it in system later");
        return;        
}//GEN-LAST:event_issueActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new truckdispatch("truck1",10.0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField charge;
    private javax.swing.JButton issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel truckname;
    private javax.swing.JLabel volume;
    // End of variables declaration//GEN-END:variables

}
